cacheFolder: ./.yarn/cache
nodeLinker: node-modules # todo: test pnp or pnpm mode
yarnPath: .yarn/releases/yarn-4.1.1.cjs
changesetIgnorePatterns:
  - "**/*.stories.{js,ts}"
  - "**/stories/*.{js,ts}"
defaultSemverRangePrefix: "^"
enableColors: true
enableTelemetry: false
injectEnvironmentFiles:
  - ".env?"

## Default settings for yarn init packages
initScope: "spectrum-css"
initFields:
  author: Adobe
  license: "Apache-2.0"
  bugs.url: "https://github.com/adobe/spectrum-css/issues"
  main: "dist/index.css"
  publishConfig.access: "public"

npmPublishAccess: "public"
npmPublishRegistry: "https://npm.pkg.github.com"
npmAlwaysAuth: false

npmScopes:
  a4u:
    npmRegistryServer: "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-a4u-release/"
    npmAlwaysAuth: true
    npmAuthToken: ${ARTIFACTORY_API_TOKEN:-""}
    npmAuthIdent: ${NPM_EMAIL:-""}:${NPM_AUTH:-""}
